name: Build Android APK

on:
  push:
    branches:
      - beta
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Java
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.4' # Or your preferred version
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --flavor github

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v7
        with:
          name: trireme-release-apk
          path: build/app/outputs/flutter-apk/app-github-release.apk
